### ISSUE TITLE
some questions about traing the converted data

### ISSUE THREAD

**Issue by visonpon** [BartMoyaers/BvhToDeepMimic#15]
Hi @BartMoyaers , thanks for your generous sharing of this work, i have tried to use some of the converted txt to train deepmimic , but all the results are bad. So hope you can give some help.

Fisrt, are there any other arguments you modified in the args.txt except for the motion_file?
Second, how long did you trained for each motion?
Third, since the converted txt are bigger than the orignal deepmimic txt, did you split it into smaller parts or just train on it?

what's more, I also tried to convert other form of bvh file to txt by modifing the settings.jon, but encountered the "Matrix must be orthogonal, i.e. its tranpose should he ist inverse" error. the difference between the bvh file is only the joint's name and the order of rotationChannelNames(mine is Zrotation,Xortation,Yrotaion).
Hope can recive your responce ,thanks~

**Comment by zzzbbs** [comment]
> Hi @BartMoyaers , thanks for your generous sharing of this work, i have tried to use some of the converted txt to train deepmimic , but all the results are bad. So hope you can give some help.
> 
> Fisrt, are there any other arguments you modified in the args.txt except for the motion_file? Second, how long did you trained for each motion? Third, since the converted txt are bigger than the orignal deepmimic txt, did you split it into smaller parts or just train on it?
> 
> what's more, I also tried to convert other form of bvh file to txt by modifing the settings.jon, but encountered the "Matrix must be orthogonal, i.e. its tranpose should he ist inverse" error. the difference between the bvh file is only the joint's name and the order of rotationChannelNames(mine is Zrotation,Xortation,Yrotaion). Hope can recive your responce ,thanks~

Hi, visonpon.
I 'm facing the same problem of yours. Have you solved this problem? Could you give me some guidance? Thanks~

**Comment by visonpon** [comment]
@zzzbbs modify the setting.json file according to your bvh , and pay atttention to the jointAssignents,rootRotjoinmts,position/rotationchannelnames. what's more, set the scale to a proper value.
